island-formulator/config/routes.rb
Rails.application.routes.draw do
  get "dashboard/show"
  resources :batches
  resources :recipes
  get "users/new"
  get "users/create"

  resource :session
  resources :users, only: [ :new, :create ]
  resources :passwords, param: :token
  resources :ingredients

  resources :inventory_items
  resources :batches, only: [ :index, :show, :new, :create, :destroy ]


  root "dashboard#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

island-formulator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

island-formulator/app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :made_on, presence: true
end

island-formulator/app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

island-formulator/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  # Every ingredient must belong to a user
  belongs_to :user

  # This allows us to say @ingredient.tags and get a list of all tags!
  has_many :ingredient_tags, dependent: :destroy
  has_many :tags, through: :ingredient_tags
  has_many :inventory_items, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
  has_one_attached :photo

  validates :name, presence: true
  validates :category, presence: true
  validates :user, presence: true # ensures every ingredient has user present
end

island-formulator/app/models/ingredient_tag.rb
class IngredientTag < ApplicationRecord
  # This is the bridge. It belongs to both sides.
  # It's like a link in a chain connecting an Ingredient to a Tag.
  belongs_to :ingredient
  belongs_to :tag
end

island-formulator/app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
  has_one_attached :photo # allows us to attach a photo to each inventory item (receipt, etc.)

  validates :ingredient_id, presence: true
  validates :purchase_date, presence: true
end

island-formulator/app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_one_attached :photo
  has_many :batches, dependent: :destroy

  # This is the magic line for our nested form!
  # It allows us to save ingredients at the same time we save the recipe.
  # allow_destroy: true lets us delete ingredients from a recipe.
  # reject_if: :all_blank prevents saving empty rows.
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
  validates :method, presence: true
  validates :product_type, presence: true

  validate :must_have_at_least_one_ingredient

  private
  def must_have_at_least_one_ingredient
    if recipe_ingredients.reject(&:marked_for_destruction?).empty?
      errors.add(:base, "Recipe must have at least one ingredient")
    end
  end
end

island-formulator/app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  belongs_to :ingredient
end

island-formulator/app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

island-formulator/app/models/tag.rb
class Tag < ApplicationRecord
  # A Tag can be associated with many Ingredients through IngredientTags.
  has_many :ingredient_tags, dependent: :destroy
  has_many :ingredients, through: :ingredient_tags

  validates :name, presence: true, uniqueness: true
end

island-formulator/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :inventory_items, dependent: :destroy
  has_many :batches, dependent: :destroy

  # validations for better error messages
  validates :email_address, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }, confirmation: true
  validates :password_confirmation, presence: true
end

island-formulator/app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :require_authentication

  # GET /batches or /batches.json
  def index
    @batches = current_user.batches.includes(:recipe).order(made_on: :desc)
  end

  # GET /batches/1 or /batches/1.json
  def show
    @batch = current_user.batches.find(params[:id])
  end

  # GET /batches/new
  def new
    @batch = current_user.batches.build(recipe_id: params[:recipe_id], made_on: Date.today)
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches or /batches.json
  def create
    @batch = current_user.batches.build(batch_params)


    if @batch.save
      redirect_to batches_path, notice: "Batch was successfully logged."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def batch_params
      params.require(:batch).permit(:recipe_id, :made_on, :notes)
    end
end

island-formulator/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_authentication
  before_action :set_recipe, only: [ :show, :edit, :update, :destroy ]

  # GET /recipes or /recipes.json for the current user
  def index
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
    # five blank ingredients for the form
    5.times { @recipe.recipe_ingredients.build }
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

      if @recipe.save
        redirect_to @recipe, notice: "Recipe was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "Recipe was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!
    redirect_to recipes_url, notice: "Recipe was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = current_user.recipes.find(params[:id])
    end

    # Ingredient attributes are nested in the recipe form, so we need to permit them here as well.
    def recipe_params
      params.require(:recipe).permit(
      :title,
      :product_type,
      :method,
      :photo,
      recipe_ingredients_attributes: [ :id, :ingredient_id, :quantity, :_destroy ]
      )
    end
end

island-formulator/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # allowing unathenticated users to sign up, but not to access any other actions
  allow_unauthenticated_access only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       session = @user.sessions.create!
      cookies.signed[:session_id] = { value: session.id, httponly: true }

      redirect_to root_path, notice: "Welcome! Your account has been created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  # Access parameters from the form requesting password for security
  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

island-formulator/app/helpers/application_helper.rb
module ApplicationHelper
end

island-formulator/app/helpers/batches_helper.rb
module BatchesHelper
end

island-formulator/app/helpers/dashboard_helper.rb
module DashboardHelper
end

island-formulator/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

island-formulator/app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

island-formulator/app/helpers/recipes_helper.rb
module RecipesHelper
end

island-formulator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="min-h-screen bg-transparent">
  <head>
    <title><%= content_for(:title) || "Island Formulator" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Island Formulator">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col bg-gradient-to-l from-[#f5f7f8] via-[#f4ce14] to-[#379777] w-full">

    <!-- HEADER -->
    <header class="mt-2 bg-black shadow-lg w-full">
      <div class="mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-18">

          <!-- Left side -->
          <div class="flex-shrink-0 flex items-center gap-4">
            <%= link_to "🪻ℑ𝔰𝔩𝔞𝔫𝔡 𝔉𝔬𝔯𝔪𝔲𝔩𝔞𝔱𝔬𝔯", root_path,
                class: "text-4xl font-bold text-white py-2" %>

            <% if authenticated? %>
              <%= link_to "My Recipes", recipes_path, class: "text-gray-500 hover:text-green-600 transition-colors font-semibold mt-4" %>
              <%= link_to "Inventory", inventory_items_path, class: "text-gray-500 hover:text-yellow-300 transition-colors font-semibold mt-4" %>
              <%= link_to "Batches", batches_path, class: "text-gray-500 hover:text-purple-300 transition-colors font-semibold mt-4" %>
              <%= link_to "My Ingredients", ingredients_path, class: "text-gray-500 hover:text-blue-300 transition-colors font-semibold mt-4" %>
            <% end %>
          </div>

          <!-- Right side -->
          <nav class="hidden md:flex space-x-6">
            <div class="flex items-center gap-4">
              <% if authenticated? %>
                <span class="text-sm text-gray-500">
                  <%= Current.user.email_address %>
                </span>

                <%= button_to "Logout", session_path, method: :delete,
                    class: "px-4 py-2 bg-gray-700 text-gray-300 hover:text-red-500 font-medium rounded-md transition-colors" %>

              <% else %>
                <div class="flex space-x-2">
                  <%= link_to "Sign Up", new_user_path,
                      class: "px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-100 rounded-md transition-colors" %>

                  <%= link_to "Login", new_session_path,
                      class: "px-4 py-2 text-sm font-medium text-white bg-gray-700 hover:bg-gray-100 rounded-md transition-colors" %>
                </div>
              <% end %>
            </div>
          </nav>

        </div>
      </div>
    </header>

    <!-- MAIN CONTENT -->
    <main class="flex-1 bg-transparent w-full">
      <%= yield %>
    </main>

  </body>
</html>